name: Test Matrix Commits
on:
  push:
    branches:
      - main
jobs:
  matrix-commit:
    name: Matrix Commit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        stream:
          - a
          - b
          - c
          - d
          - e
    steps:
      - name: Make changes
        run: echo "${{ matrix.stream }}" >> log.txt

      - name: Pull latest commits
        run: git pull --rebase --autostash

      - name: Commit new changes
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          CI_COMMIT_MESSAGE: "Commit change ${{ matrix.stream }}"
          CI_COMMIT_AUTHOR: HyBB-8
        with:
          commit_user_name: ${{ env.CI_COMMIT_AUTHOR }}
          commit_message: ${{ env.CI_COMMIT_MESSAGE }}
          file_pattern: '*'
