name: Test Matrix Commits
on:
  push:
    branches:
      - main
jobs:
  matrix-commit:
    name: Matrix Commit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        stream:
          - a
          - b
          - c
          - d
          - e
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Make changes
        run: echo "$(date)" >> ${{ matrix.stream }}.txt

      - name: Pull latest commits
        run: sleep $(shuf -i 1-5 -n 1) && git pull --rebase --autostash
      - name: Commit new changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        continue-on-error: true
        env:
          CI_COMMIT_MESSAGE: "[skip ci] Commit change ${{ matrix.stream }}"
          CI_COMMIT_AUTHOR: HyBB-8
        with:
          commit_user_name: ${{ env.CI_COMMIT_AUTHOR }}
          commit_message: ${{ env.CI_COMMIT_MESSAGE }}
          file_pattern: '*'
      - name: Retry pull latest commits
        if: steps.commit.outcome != 'success'
        run: sleep $(shuf -i 1-5 -n 1) && git pull --rebase --autostash
      - name: Retry commit new changes
        if: steps.commit.outcome != 'success'
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          CI_COMMIT_MESSAGE: "[skip ci] Commit change ${{ matrix.stream }}"
          CI_COMMIT_AUTHOR: HyBB-8
        with:
          commit_user_name: ${{ env.CI_COMMIT_AUTHOR }}
          commit_message: ${{ env.CI_COMMIT_MESSAGE }}
          file_pattern: '*'
